name: ikuuu Checkin

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点执行
  workflow_dispatch:  # 手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Run ikuuu Checkin
        env:
          IKUUU_ACCOUNTS: ${{ secrets.IKUUU_ACCOUNTS }}
          IKUUU_TG_BOT_TOKEN: ${{ secrets.IKUUU_TG_BOT_TOKEN }}
          IKUUU_TG_CHAT_ID: ${{ secrets.IKUUU_TG_CHAT_ID }}
        run: |
          node ikuuu.js
